name: Generate Snake Animation

on:
  schedule:
    # Update every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - name: Generate GitHub Contribution Grid Snake
        uses: Platane/snk@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_user_name: Sindhura492
          file_name_generated: github-contribution-grid-snake.svg
          file_name_generated_dark: github-contribution-grid-snake-dark.svg
